### ISSUE TITLE
Add PAM module

### ISSUE THREAD

**Issue by josephlr** [google/fscrypt#4]
As mentioned in the `README`, the idea of protecting directories with a login passphrase is incomplete without a [PAM module](http://www.linux-pam.org/Linux-PAM-html). This PAM module will need to support the following functionality:

- Automatically re-wrapping a user's login protector when their PAM passphrase changes.
- Automatically unlocking directories on login

The road map for changes to incorporate the PAM module is as follows:

- [x] (#21) Refactoring the `pam` package to support the additional functionality. 
- [x] (#3, #18) Improvements to the `actions` package making unlocking Policies easier. See #3 and #18 
- [x] (#25) Writing the PAM module itself. This will be a package exporting the correct identifiers built as a `.so`.
- [x] (#25) Adding build support in the Makefile
- [x] (#25) Updating the Documentation
